"""openFDA's published field catalogue, the single source of truth for what openFDA offers.

``fields.json`` is generated by ``scripts/refresh_openfda_fields.py`` from the YAML field
definitions openFDA publishes for every dataset. Everything the application needs to know
about openFDA's structure - which datasets exist, which fields each has, which label sections
can be requested - is derived from it rather than typed out by hand. Hand-maintained copies
drifted: a hand-written label-section list allowed 42 of the 92 sections openFDA publishes.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

CATALOGUE_PATH = Path(__file__).with_name("fields.json")
# Label fields that identify or version a label rather than holding its text.
LABEL_METADATA_FIELDS = frozenset({"set_id", "id", "version", "effective_time"})


@lru_cache
def catalogue() -> dict[str, dict[str, dict[str, Any]]]:
    data: dict[str, dict[str, dict[str, Any]]] = json.loads(CATALOGUE_PATH.read_text())
    return data


def datasets() -> frozenset[str]:
    return frozenset(catalogue())


def fields(dataset: str) -> dict[str, dict[str, Any]]:
    return catalogue().get(dataset, {})


@lru_cache
def label_sections() -> frozenset[str]:
    """Every text section a drug label can carry, prescription and OTC alike.

    Tables (``*_table``) are returned alongside their section automatically, and harmonised
    ``openfda.*`` fields are metadata, so neither is listed here.
    """
    return frozenset(
        name
        for name in fields("drug/label")
        if not name.startswith("openfda.")
        and not name.endswith("_table")
        and name not in LABEL_METADATA_FIELDS
    )
